// Pure decision logic for when the apprentice may ask a question.
// No SDK, no DOM — unit-tested in pauseGate.test.ts.

export type PendingEvent = { topic: string; text: string };

export type GateInput = {
  now: number;
  connected: boolean;
  offRecord: boolean;
  /** "Give me a moment": questions held until this timestamp (0 = not holding). */
  holdUntil: number;
  lastActivity: number;
  lastSpeech: number;
  agentSpeaking: boolean;
  lastNudge: number;
  pauseMs: number;
  speechQuietMs: number;
  cooldownMs: number;
  pending: readonly PendingEvent[];
  askedTopics: ReadonlySet<string>;
};

export type WaitReason =
  | "disconnected"
  | "off-record"
  | "no-events"
  | "holding"
  | "active"
  | "speaking"
  | "agent-speaking"
  | "cooldown";

export type GateDecision =
  | { action: "nudge"; events: PendingEvent[]; dropped: PendingEvent[] }
  | { action: "drop-asked"; dropped: PendingEvent[] }
  | { action: "wait"; reason: WaitReason };

export function decideNudge(s: GateInput): GateDecision {
  if (!s.connected) return { action: "wait", reason: "disconnected" };
  if (s.offRecord) return { action: "wait", reason: "off-record" };
  if (s.pending.length === 0) return { action: "wait", reason: "no-events" };
  if (s.holdUntil > s.now) return { action: "wait", reason: "holding" };
  if (s.now - s.lastActivity < s.pauseMs) return { action: "wait", reason: "active" };
  if (s.agentSpeaking) return { action: "wait", reason: "agent-speaking" };
  if (s.now - s.lastSpeech < s.speechQuietMs) return { action: "wait", reason: "speaking" };
  if (s.now - s.lastNudge < s.cooldownMs) return { action: "wait", reason: "cooldown" };
  const dropped = s.pending.filter((e) => s.askedTopics.has(e.topic));
  const events = s.pending.filter((e) => !s.askedTopics.has(e.topic));
  if (events.length === 0) return { action: "drop-asked", dropped };
  return { action: "nudge", events, dropped };
}

/** Topic key for an app event: one key per field per invoice, so a repeated
 *  change to the same field is never asked about twice. */
export function appTopic(invoiceId: string, field: string): string {
  return `app:${invoiceId}:${field.toLowerCase()}`;
}

/** Topic key for a vision event: normalize the one-line observation so
 *  "Cost center changed from 4711 to 0400" and a later change back to 4711
 *  collapse to the same topic. Keeps the first six words, drops digits. */
export function visionTopic(text: string): string {
  const words = text
    .toLowerCase()
    .replace(/[0-9]/g, "")
    .replace(/[^a-z\s]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 6);
  return `vision:${words.join("-")}`;
}

export function buildNudgeMessage(events: readonly PendingEvent[], idleMs: number): string {
  return (
    `[APP SIGNAL — generated by the app, NOT spoken by the expert] ` +
    `No keyboard/mouse input for ${(idleMs / 1000).toFixed(1)}s and no speech. ` +
    `Screen events since your last question:\n- ${events.map((e) => e.text).join("\n- ")}\n` +
    `If one of these is a decision whose reason is NOT visible on screen, ask ONE short "why" question now ` +
    `(prefer rules, limits, exceptions, who to ask). Never ask about something visible. ` +
    `If nothing is worth asking, call skip_turn and say nothing.`
  );
}
